### ISSUE TITLE
2019-12-16-blog-01 双曲二倍角有错

### ISSUE THREAD

**Issue by XavierOwen** [Magolor/magolor.github.io#36]

**Comment by Magolor** [comment]
已经修正！谢谢大佬指出错误！

大佬在这里发issue我有可能看不到（我好像没收到Github通知），可以在文章的评论区下面回复我，这样我会收到通知。是我的评论区坏了吗？（我不太确定，有的时候我这里显示Network Error，估计是Github的原因）

**Comment by Magolor** [comment]
> _No description provided._

已经修正！谢谢大佬指出错误！

大佬在这里发issue我有可能看不到（我好像没收到Github通知），可以在文章的评论区下面回复我，这样我会收到通知。是我的评论区坏了吗？（我不太确定，有的时候我这里显示Network Error，估计是Github的原因）
